jobs:
  - name : rsyncresotest-manifest6
    type: manifest
    steps:
      - PUT: rsyncresotest-image18
      - GET: rsyncresotest-image19
      - GET: rsyncresotest-dockeroption1
      - GET: rsyncresotest-param1
      - GET: rsyncresotest-image17
